# -*- coding: utf-8 -*-
"""User-managed fullscreen-video keymap for Dex Hub source switching.

Kodi settings cannot natively bind remote buttons.  This module captures the
physical button code in a small modal window, writes only Dex Hub's own
keymap file under the user's profile, and reloads keymaps immediately.  It
never edits the user's other keymap files.
"""
import json
import os
import xml.sax.saxutils

import xbmc
import xbmcaddon
import xbmcgui
import xbmcvfs


ADDON_ID = 'plugin.video.dexhub'
WINDOW_ID = 10000
KEYMAP_FILENAME = 'dexhub-switch-source.xml'
SETTING_ID = 'switch_source_keymap_data'
ACTION = 'RunPlugin(plugin://plugin.video.dexhub/?action=switch_source)'


def _addon():
    return xbmcaddon.Addon(ADDON_ID)


def _addon_path():
    return _addon().getAddonInfo('path')


def _keymap_path():
    folder = xbmcvfs.translatePath('special://profile/keymaps/')
    return os.path.join(folder, KEYMAP_FILENAME)


def _safe_action_ids():
    """Actions that must never be claimed by a generated fullscreen binding."""
    names = (
        'ACTION_NAV_BACK', 'ACTION_PREVIOUS_MENU', 'ACTION_STOP',
        'ACTION_SHOW_INFO', 'ACTION_PARENT_DIR', 'ACTION_SHOW_GUI',
    )
    return set(getattr(xbmcgui, name, -999999) for name in names)


def _read_config():
    try:
        raw = _addon().getSetting(SETTING_ID) or ''
        data = json.loads(raw) if raw else {}
        return data if isinstance(data, dict) else {}
    except Exception:
        return {}


def _write_config(data):
    try:
        _addon().setSetting(SETTING_ID, json.dumps(data or {}, ensure_ascii=False, sort_keys=True))
    except Exception:
        pass


def describe_binding(data=None):
    data = data if isinstance(data, dict) else _read_config()
    kind = data.get('kind') or ''
    if kind == 'yellow':
        return 'Yellow remote button'
    if kind == 'keyboard_s':
        return 'Keyboard S'
    if kind == 'raw':
        return 'Button code %s' % data.get('code', '?')
    return 'Not configured'


def _xml_for_binding(data):
    kind = data.get('kind') or ''
    if kind == 'yellow':
        keyboard = ''
        remote = '      <yellow>%s</yellow>\n' % ACTION
    elif kind == 'keyboard_s':
        keyboard = '      <s>%s</s>\n' % ACTION
        remote = ''
    elif kind == 'raw':
        try:
            code = int(data.get('code'))
        except Exception:
            raise ValueError('Invalid button code')
        if code <= 0:
            raise ValueError('Invalid button code')
        # Kodi does not expose the originating input device to Python for all
        # remotes.  Put the captured code in both scopes; only the matching
        # device delivers it, and the binding remains fullscreen-video only.
        key = xml.sax.saxutils.escape(str(code), {'"': '&quot;'})
        keyboard = '      <key id="%s">%s</key>\n' % (key, ACTION)
        remote = '      <key id="%s">%s</key>\n' % (key, ACTION)
    else:
        raise ValueError('Unknown binding')
    return '''<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Dex Hub. Active only while fullscreen video is playing. -->
<keymap>
  <fullscreenvideo>
    <keyboard>
%s    </keyboard>
    <remote>
%s    </remote>
  </fullscreenvideo>
</keymap>
''' % (keyboard, remote)


def _reload_keymaps():
    try:
        xbmc.executebuiltin('Action(reloadkeymaps)')
    except Exception:
        pass


def save_binding(data):
    """Atomically install the generated map and activate it immediately."""
    payload = _xml_for_binding(data)
    target = _keymap_path()
    folder = os.path.dirname(target)
    try:
        if folder and not os.path.exists(folder):
            os.makedirs(folder, exist_ok=True)
        tmp = target + '.tmp'
        with open(tmp, 'w', encoding='utf-8') as fh:
            fh.write(payload)
        os.replace(tmp, target)
    except Exception as exc:
        xbmc.log('[DexHub] keymap write failed: %s' % exc, xbmc.LOGERROR)
        return False
    _write_config(data)
    _reload_keymaps()
    return True


def remove_binding():
    target = _keymap_path()
    try:
        if os.path.exists(target):
            os.remove(target)
    except Exception as exc:
        xbmc.log('[DexHub] keymap removal failed: %s' % exc, xbmc.LOGWARNING)
        return False
    _write_config({})
    _reload_keymaps()
    return True


class _KeyCaptureDialog(xbmcgui.WindowXMLDialog):
    """Wait for one physical key/remote action, or Back to cancel."""

    def __init__(self, *args, **kwargs):
        self.result = None
        self.error = ''
        super().__init__(*args, **kwargs)

    def onInit(self):
        win = xbmcgui.Window(WINDOW_ID)
        win.setProperty('dexhub.keycapture.title', 'Source switch shortcut')
        win.setProperty('dexhub.keycapture.message', 'Press the key or remote button to switch source. Press Back to cancel.')
        win.setProperty('dexhub.keycapture.error', '')

    def onAction(self, action):
        action_id = action.getId()
        if action_id in (getattr(xbmcgui, 'ACTION_NAV_BACK', -1),
                         getattr(xbmcgui, 'ACTION_PREVIOUS_MENU', -2)):
            self.close()
            return
        if action_id in _safe_action_ids():
            self.error = 'That control is reserved for Kodi playback/navigation.'
            xbmcgui.Window(WINDOW_ID).setProperty('dexhub.keycapture.error', self.error)
            return
        try:
            code = int(action.getButtonCode() or 0)
        except Exception:
            code = 0
        if code <= 0:
            self.error = 'Kodi did not provide a bindable button code. Try another control.'
            xbmcgui.Window(WINDOW_ID).setProperty('dexhub.keycapture.error', self.error)
            return
        self.result = {'kind': 'raw', 'code': code}
        self.close()


def _capture_raw_binding():
    try:
        dialog = _KeyCaptureDialog('dexhub_key_capture.xml', _addon_path(), 'Default', '1080i')
        dialog.doModal()
        result = dialog.result
        del dialog
        return result
    except Exception as exc:
        xbmc.log('[DexHub] key capture failed: %s' % exc, xbmc.LOGWARNING)
        return None
    finally:
        win = xbmcgui.Window(WINDOW_ID)
        for prop in ('dexhub.keycapture.title', 'dexhub.keycapture.message', 'dexhub.keycapture.error'):
            try:
                win.clearProperty(prop)
            except Exception:
                pass


def configure():
    """Let the user capture a button or choose a known-safe preset."""
    choices = [
        'Press a key or remote button now',
        'Use the yellow remote button',
        'Use keyboard S',
    ]
    selected = xbmcgui.Dialog().select('Source switch shortcut', choices)
    if selected < 0:
        return False
    if selected == 0:
        binding = _capture_raw_binding()
        if not binding:
            return False
    elif selected == 1:
        binding = {'kind': 'yellow'}
    else:
        binding = {'kind': 'keyboard_s'}
    message = ('This binding applies only during fullscreen video playback. '
               'It may replace Kodi\'s existing action for that button.')
    if not xbmcgui.Dialog().yesno('Dex Hub', message, nolabel='Cancel', yeslabel='Save'):
        return False
    if not save_binding(binding):
        xbmcgui.Dialog().notification('Dex Hub', 'Could not save the source-switch shortcut.', xbmcgui.NOTIFICATION_ERROR, 3500)
        return False
    xbmcgui.Dialog().notification('Dex Hub', 'Source switch shortcut saved: %s' % describe_binding(binding), xbmcgui.NOTIFICATION_INFO, 3500)
    return True


def show_status():
    configured = _read_config()
    message = 'Current source-switch shortcut: %s' % describe_binding(configured)
    if not configured:
        message += '\n\nChoose Configure source switch shortcut to create one.'
    xbmcgui.Dialog().ok('Dex Hub', message)

